<<<<<<< HEAD
weights: ./models/kinetics-st_gcn.pt
=======
weights: ./models/st_gcn.kinetics.pt
>>>>>>> e7024ac16714d6d6ac911f7cfb2910aea1940b15

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'
    
# training
device: [0]